# frozen_string_literal: true

require_relative "authorization_module/version"
require_relative 'authorization_module/config/configuration'
require_relative 'authorization_module/config/authorization_configuration'
require_relative 'authorization_module/config/error_configuration'
require_relative "authorization_module/abac/attribute_provider_factory"
require_relative "authorization_module/abac/condition_serializer"
require_relative "authorization_module/abac/null_attribute_provider"
require_relative 'authorization_module/errors/unauthorized_error'
require_relative 'authorization_module/errors/unauthenticated_error'
require_relative 'authorization_module/errors/missing_config_error'
require_relative 'authorization_module/errors/api_error'
require_relative 'authorization_module/models/identity'
require_relative 'authorization_module/models/permission'
require_relative 'authorization_module/models/policy'
require_relative 'authorization_module/models/role'
require_relative 'authorization_module/models/role_grant'
require_relative 'authorization_module/models/abac/condition'
require_relative 'authorization_module/railtie'
require_relative 'authorization_module/policy_enforcer'
require_relative 'authorization_module/authorization_service'

module AuthorizationModule; end
