default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV.fetch("DB_DEVELOPMENT_USER") { 'postgres' } %>
  password: <%= ENV.fetch("DB_DEVELOPMENT_PASSWORD") { 'password' } %>
  host: <%= ENV.fetch("DB_DEVELOPMENT_HOST") { 'localhost' } %>

development:
  <<: *default
  database: authorization_module_development

test:
  <<: *default
  database: authorization_module_test